### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by finnie2006** [Renaud11232/icecast-autodj#2]
Ezstream error 2 missing url

**Comment by finnie2006** [comment]
https://ibb.co/0jX1P6f

**Comment by Renaud11232** [comment]
Hello,

What version of ezstream is installed ? (run `ezstream -V` to check it).

If you have a version starting with `0.`, use `ezstream.v0.xml`.
If you have a version starting with `1.` use the other one.

If that's already the case, can you give the output from `ezstream -V` and your configuration file. Make sure it doesn't contain any private information, like passwords or IP adresses before sending it.

Thanks

**Comment by finnie2006** [comment]
0.5.6

**Comment by finnie2006** [comment]
I maded a config for ezstream 1 , but i run 0.5.6 how can i update to ezstream 1
![image](https://user-images.githubusercontent.com/57916807/110593798-52cc9880-817c-11eb-9582-c9277da72c49.png)

**Comment by finnie2006** [comment]
![image](https://user-images.githubusercontent.com/57916807/110592842-13ea1300-817b-11eb-856a-89e9dea0e3a9.png)

**Comment by finnie2006** [comment]
i use this now to update but i get this error whem configuring

configure: error: libtag_c is missing

**Comment by finnie2006** [comment]
i used 0.5 for now it worked● ezstream.service - EZStream AutoDJ
   Loaded: loaded (/etc/systemd/system/ezstream.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2021-03-10 09:08:58 CET; 2s ago
  Process: 10367 ExecStart=/usr/bin/ezstream -c /etc/ezstream/ezstream.xml (code=exited, status=0/SUCCESS)
 Main PID: 10367 (code=exited, status=0/SUCCESS)

Mar 10 09:08:58 raspberrypi systemd[1]: Started EZStream AutoDJ.
Mar 10 09:08:58 raspberrypi ezstream[10367]: ezstream: Connected to http://stream.radioannabel.ml:8000/autodj
Mar 10 09:08:58 raspberrypi ezstream[10367]: ezstream: /etc/ezstream/playlist.m3u: No such file or directory
Mar 10 09:08:58 raspberrypi systemd[1]: ezstream.service: Succeeded.



but how can i add music

**Comment by finnie2006** [comment]
now i get this after reboot

pi@raspberrypi:~/ezstream $ sudo systemctl status ezstream
● ezstream.service - EZStream AutoDJ
   Loaded: loaded (/etc/systemd/system/ezstream.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2021-03-10 09:31:47 CET; 2s ago
  Process: 1161 ExecStart=/usr/bin/ezstream -c /etc/ezstream/ezstream.xml (code=exited, status=0/SUCCESS)
 Main PID: 1161 (code=exited, status=0/SUCCESS)

Mar 10 09:31:47 raspberrypi systemd[1]: Started EZStream AutoDJ.
Mar 10 09:31:47 raspberrypi ezstream[1161]: ezstream: Connection to http://stream.radioannabel.ml:8000/autodj failed: Login failed
Mar 10 09:31:47 raspberrypi systemd[1]: ezstream.service: Succeeded.
pi@raspberrypi:~/ezstream $

**Comment by finnie2006** [comment]
i reinstall it worked but after every reboot it doesnt work login

**Comment by finnie2006** [comment]
Mar 10 10:58:10 raspberrypi ezstream[9679]: WARNING: libsndfile may ignore -r and perform fseek's on the input.
Mar 10 10:58:10 raspberrypi ezstream[9679]: Compile without libsndfile if this is a problem.
Mar 10 10:58:10 raspberrypi ezstream[9679]: ezstream: Streaming ``Milky Chance - Stolen Dance''
Mar 10 10:58:10 raspberrypi ezstream[9679]: /home/pi/Desktop/Geniaal/073: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: The: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Weeknd: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: I: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Feel: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: It: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Coming.mp3: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: WARNING: libsndfile may ignore -r and perform fseek's on the input.
Mar 10 10:58:10 raspberrypi ezstream[9679]: Compile without libsndfile if this is a problem.

**Comment by finnie2006** [comment]
It works now but whe i do the refresh playlist command it says that it not exist

**Comment by Renaud11232** [comment]
The latest version of ezstream is not always available in the default distro repository, if you really want the latest version you can probably install it manually. But it is not needed.

I saw in previous deleted messages that had this issue : 
```
Mar 10 10:58:10 raspberrypi ezstream[9679]: /home/pi/Desktop/Geniaal/073: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: The: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Weeknd: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: I: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Feel: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: It: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Coming.mp3: No such file or directory
```

This is likely due to the fact that the file name or path contained whitespaces. To prevent this in the configuration you can change the following line : 
```xml
<decode>madplay --very-quiet -b 16 -R 44100 -S -o raw:- @T@</decode>
```
And replace them with this : 
```xml
<decode>madplay --very-quiet -b 16 -R 44100 -S -o raw:- "@T@"</decode>
```
(added double quotes around `@T@`, I'll update the example files)

> It works now but whe i do the refresh playlist command it says that it not exist

What exact command did you type ? And what is the output of that command ?

**Comment by finnie2006** [comment]
i typed this refresh_playlist

and getted this   pi@raspberrypi:~ $ sudo refresh_playlist
sudo: refresh_playlist: command not found
pi@raspberrypi:~ $ 




So when i make the m3u file and there is blank spce do this command?    <decode>madplay --very-quiet -b 16 -R 44100 -S -o raw:- "@T@"</decode>

**Comment by finnie2006** [comment]
pi@raspberrypi:~/icecast-autodj $ <decode>madplay --very-quiet -b 16 -R 44100 -S -o raw:- "@T@"</decode>
-bash: syntax error near unexpected token `newline'

or do i need to put that line in a config file

**Comment by finnie2006** [comment]
That line worked 
but this command doesnt work for me refresh_playlist
And how can i add fades

**Comment by Renaud11232** [comment]
The modification I wrote earlier is in the ezstream configuration, not a command to manually type in.

The `refresh_playlist` script is located in the `script` folder of this repository.

For the `sudo refresh_playlist` command to work, the script needs to be executable and placed in a directory listed in your `$PATH` environment variable such as `/usr/local/bin`.
To make sure it is executable, you can type `sudo chmod +x /path/to/where/the/script/is/refresh_playlist`

Alternatively, if you don't want to place it in your `$PATH`, you can also run it using `sudo ./refresh_playlist` assuming it is in the current directory and that it is executable or `sudo /absolute/path/to/refresh_playlist`.

I don't believe that ezstream provides a way to fade between songs.

I hope that helped

**Comment by finnie2006** [comment]
https://ibb.co/cFrtnSg

**Comment by finnie2006** [comment]
What is the exact location somi can cp it to my folder

**Comment by finnie2006** [comment]
https://ibb.co/7vpkjLml

**Comment by tmagis** [comment]
Hello,

I see that you have some issues with the file locations here.

You can see here 
![image](https://user-images.githubusercontent.com/35865709/110698939-906a0980-81ee-11eb-8220-5a3db2f6c31c.png)

(underlined in blue) that there is a "~" character before the location where you are. This means "your home directory" -> "/home/pi/".

When accessing your file, you can do it via multiple ways:

~/icecast-autodj/scripts/refresh_playlist
OR
/home/pi/icecast-autodj/scripts/refresh_playlist

if you are already in /home/pi, you can also do:
./icecast-autodj/scripts/refresh_playlist

(the . at the begin means "from here")

When a file location starts with a dot . it means that you start the location description from the current location (shorter but only works from the current location). When a location starts with a / it means that you specify the absolute location, it means the complete location from the root of the hard drive. It is longer but works from everywhere.

**Comment by finnie2006** [comment]
What do i wrong https://ibb.co/JC8tTDs
https://ibb.co/nBB0dvX

I do how u explained it but it looks like the script drops an error

**Comment by finnie2006** [comment]
It drops that error

**Comment by finnie2006** [comment]
Is liquidsoap better?

**Comment by Renaud11232** [comment]
It looks like there is an issue with my scripts.
They look for a process launched in the group `icecast` but it seems that group doesn't exist.
On Ubuntu that group is automatically created when you install icecast, it looks like it's not the case on Raspbian/RaspberryOS

I don't know if liquidsoap is better, I've never used it.

CAn you type this command and give the output so I can try to see why my scripts aren't working, thanks
```bash
ps ax o user,group,cmd | grep icecast
```

**Comment by finnie2006** [comment]
i will try that today

**Comment by finnie2006** [comment]
Here is see something about fades i want thathttps://pythonhosted.org/ardj/install.html

**Comment by finnie2006** [comment]
pi@raspberrypi:~ $ ps ax o user,group,cmd | grep icecast
icecast2 icecast  /usr/bin/icecast2 -b -c /etc/icecast2/icecast.xml
icecast2 icecast  /usr/bin/ezstream -c /etc/ezstream/ezstream.xml
icecast2 icecast  sh -c madplay --very-quiet -b 16 -R 44100 -S -o raw:- "/music/188 - Sigrid - Sucker Punch.mp3" | lame --quiet --preset cbr 128 -r -s 44.1 --bitwidth 16 - -
icecast2 icecast  madplay --very-quiet -b 16 -R 44100 -S -o raw:- /music/188 - Sigrid - Sucker Punch.mp3
icecast2 icecast  lame --quiet --preset cbr 128 -r -s 44.1 --bitwidth 16 - -
pi       pi       grep --color=auto icecast
pi@raspberrypi:~ $

**Comment by finnie2006** [comment]
Maybe you can inplement fades that would be awesome

**Comment by finnie2006** [comment]
And i found a little misstype in the readme

vi /etc/icecast2/incecast.xml #Edit to your needs

Incecast= Icecast

**Comment by Renaud11232** [comment]
There was indeed an error in my scripts i had a `-g` indead of a `-G` (capital g)
The fixed script is
```bash
#!/bin/bash
USER=icecast2
GROUP=icecast
EZSTREAM_PID=$(pgrep -u $USER -G $GROUP ezstream)
kill -SIGHUP $EZSTREAM_PID
```

In the future, I may try to switch over to something more flexible than ezstream, maybe liquidsoap.
Using just ezstream I don't believe there's a way to add fades, I may look into that later.

**Comment by finnie2006** [comment]
Yeah i looked for liquidsoap but the installation tutorials are a bit messy
So i will use ezstream from you because thats more clear for me

After i changed the scripts do i need to do chmod again?

**Comment by finnie2006** [comment]
File '/bin/bash' is unwritable ]   when i nano into it

**Comment by finnie2006** [comment]
pi@raspberrypi:~ $ sudo refresh_playlist
pgrep: invalid process group: icecast
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
pi@raspberrypi:~ $


#!/bin/bash
USER=icecast2
GROUP=icecast
EZSTREAM_PID=$(pgrep -u $USER -G $GROUP ezstream)
kill -SIGUSR2 $EZSTREAM_PID

**Comment by finnie2006** [comment]
pi@raspberrypi:~ $ sudo chmod +x refresh_playlist
pi@raspberrypi:~ $ sudo refresh_playlist
pgrep: invalid process group: icecast
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
pi@raspberrypi:~ $ USER=icecast2
cast
EZSTREAM_PID=$(pgrep -u $USER -G $GROUP ezstream)
kill -SIGUSR2 $EZSTREAM_PIDpi@raspberrypi:~ $ GROUP=icecast
pi@raspberrypi:~ $ EZSTREAM_PID=$(pgrep -u $USER -G $GROUP ezstream)
pi@raspberrypi:~ $ kill -SIGUSR2 $EZSTREAM_PID
-bash: kill: (19962) - Operation not permitted
pi@raspberrypi:~ $ sudo skip_current_track
sudo: skip_current_track: command not found
pi@raspberrypi:~ $ sudo skip_current_track
sudo: skip_current_track: command not found
pi@raspberrypi:~ $ sudo skip_current_track
sudo: skip_current_track: command not found
pi@raspberrypi:~ $ ls
Bookshelf  build  Desktop  Documents  Downloads  icecast-autodj  Music  node_modules  package-lock.json  Pictures  Public  refresh_playlist  skip_current_track  src  Templates  Videos  wget-log
pi@raspberrypi:~ $ sudo chmod +x skip_current_track
pi@raspberrypi:~ $ sudo skip_current_track
sudo: skip_current_track: command not found
pi@raspberrypi:~ $

**Comment by Renaud11232** [comment]
**Don't** try to edit bash, that would break it
The snippet I sent is the actual `refresh_playlist` script.
Edit the `refresh_playlist` file and replace it with what I sent

**Comment by finnie2006** [comment]
No i did not change bash file it works now 

pi@raspberrypi:~ $ sudo /home/pi/skip_current_track
pi@raspberrypi:~ $ sudo /home/pi/refresh_playlist

Thanks, If  i can help searching for stuff for liquidsoap let me know
liquidsoap also works with multiple playlists

**Comment by finnie2006** [comment]
Is the liquidsoap version already in a working state

**Comment by Renaud11232** [comment]
The liquidsoap script I created is working, but I haven't updated the install instructions yet.
I haven't looked into adding fades yet

**Comment by finnie2006** [comment]
Will u do that next week the documentation

**Comment by finnie2006** [comment]
and what does error -2 mean

**Comment by finnie2006** [comment]
now -4

**Comment by finnie2006** [comment]
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Finished pulling Docker container image
ezstream[8]: /home/container/icecast.xml: world readable
container@pterodactyl~ Server marked as running...
ezstream[8]: /home/container/icecast.xml: world readable
ezstream[8]: /home/container/icecast.xml: ezstream configuration not recognized
ezstream[8]: /home/container/icecast.xml: ezstream configuration not recognized
[2021-03-14  11:30:05] WARN fserve/fserve_recheck_mime_types Cannot open mime types file /etc/mime.types
[2021-03-14  11:30:05] INFO main/main Icecast 2.4.4 server started
[2021-03-14  11:30:05] INFO yp/yp_update_thread YP update thread started
[2021-03-14  11:30:05] INFO connection/get_ssl_certificate No SSL capability on any configured ports
[2021-03-14  11:30:05] WARN source/source_fallback_file unable to open file "/usr/share/icecast2/web/autodj"
[2021-03-14  11:30:05] WARN source/source_fallback_file unable to open file "/usr/share/icecast2/web/live"
[2021-03-14  11:30:19] INFO fserve/fserve_client_create checking for file /style.css (/usr/share/icecast2/web/style.css)
[2021-03-14  11:30:19] INFO fserve/fserve_client_create checking for file /icecast.png (/usr/share/icecast2/web/icecast.png)
[2021-03-14  11:30:20] INFO fserve/fserve_client_create checking for file /style.css (/usr/share/icecast2/web/style.css)
[2021-03-14  11:30:20] INFO fserve/fserve_client_create checking for file /icecast.png (/usr/share/icecast2/web/icecast.png)
[2021-03-14  11:30:22] INFO fserve/fserve_client_create checking for file /style.css (/usr/share/icecast2/web/style.css)
[2021-03-14  11:30:23] INFO fserve/fserve_client_create checking for file /icecast.png (/usr/share/icecast2/web/icecast.png)

**Comment by Renaud11232** [comment]
I don't know how that docker image is made, but it seems you are giving the icecast configuration to ezstream.

**Comment by finnie2006** [comment]
Everything works
