### ISSUE TITLE
Liquidsoap 1.3.3-2 compatibility

### ISSUE THREAD

**Issue by ligi** [Renaud11232/icecast-autodj#3]
Is there a way to use this project with Liquidsoap 1.3.3-2?

Unfortunately with 1.4.4 I run into dependency problems with debian 10

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'liquidsoap-v1.4.4' instead of './liquidsoap-v1.4.4_1.4.4-ubuntu-focal-amd64-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 liquidsoap-v1.4.4 : Depends: libavcodec58 (>= 7:4.2)
                     Depends: libavformat58 (>= 7:4.2) but 7:4.1.6-1~deb10u1 is to be installed
                     Depends: libc6 (>= 2.29) but 2.28-10 is to be installed
                     Depends: libfdk-aac1 (>= 0.1.4) but it is not installable
                     Depends: libgcc-s1 (>= 3.0) but it is not installable
                     Depends: libjpeg8 (>= 8c) but it is not installable
                     Depends: libsrt1 (>= 1.4.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by Renaud11232** [comment]
Hello,

It looks like you tried to install the .deb file meant for Ubuntu. They also provide deb files for Debian. You can find them [here](https://github.com/savonet/liquidsoap/releases/tag/v1.4.4).

Let me know if that helped.

**Comment by ligi** [comment]
Thanks!
Still wondering what feature/bugfix from 1.4 is crucial so 1.3 is not an option

**Comment by Renaud11232** [comment]
For what this repository is, 1.3 will probably work just fine. But installing 1.3 is a bit harder since they didn't provide .deb files before version 1.4.3.

And I wrote this little guide using the latest version at the time. There is no other reason.

**Comment by ligi** [comment]
Thanks! Your repo was really helpful - for me 1.3 was just easier as it comes default in debian
